#!/bin/bash

echo "Reconfigure raspi-gpio-lightswitch service..."

set -e

cd "$(dirname "$0")/.."

sudo systemctl stop raspi-gpio-lightswitch
sudo cp -u raspi-gpio-lightswitch.conf /etc
sudo systemctl start raspi-gpio-lightswitch
sleep 3
systemctl status raspi-gpio-lightswitch

echo "Done."

