#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Stopping raspi-gpio-lightswitch service..."

sudo systemctl stop raspi-gpio-lightswitch
sudo systemctl disable raspi-gpio-lightswitch

echo "Removing raspi-gpio-lightswitch service..."

sudo rm -rf /lib/systemd/system/raspi-gpio-lightswitch.service
sudo rm -rf /usr/local/bin/raspi-gpio-lightswitch.py

if [ -e /etc/raspi-gpio-lightswitch.conf ]
  then
    read -p "Delete '/etc/raspi-gpio-lightswitch.conf' configuration file? (y/N)" delfile
    if [ "$delfile" == "y" -o "$delfile" == "Y" ]
      then
        echo "Deleting configuration file."
        sudo rm -rf /etc/raspi-gpio-lightswitch.conf
    fi
fi

echo "raspi-gpio-lightswitch service uninstalled."
