#!/bin/bash

set -e

cd "$(dirname "$0")/.."

echo "Updating raspi-gpio-lightswitch service..."

if [ -e /etc/raspi-gpio-lightswitch.conf ]
  then
    read -p "Overwrite existing configuration file '/etc/raspi-gpio-lightswitch.conf' (y/N)?" ov
  else
    ov="y"
fi

if [ "$ov" == "y" -o "$ov" == "Y" ]
  then
    sudo cp raspi-gpio-lightswitch.conf /etc
fi

echo "Updating service script '/usr/local/bin/raspi-gpio-lightswitch.py' (temporarily stopping service)"
sudo systemctl stop raspi-gpio-lightswitch

sudo cp -u raspi-gpio-lightswitch.py /usr/local/bin/
sudo chmod +x /usr/local/bin/raspi-gpio-lightswitch.py

sudo cp -u raspi-gpio-lightswitch.service /lib/systemd/system

echo "Restarting raspi-gpio-lightswitch service..."
sudo systemctl daemon-reload
sudo systemctl start raspi-gpio-lightswitch
sleep 3
systemctl status raspi-gpio-lightswitch

echo "raspi-gpio-lightswitch service updated."
